#!/usr/bin/env python3
"""Write build.ninja and objdiff.json for the Summoner matching decomp."""

import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))


def modules():
    path = os.path.join(ROOT, "config", "modules.txt")
    found = []
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            rel = line.split("pccode\\", 1)[-1].replace("\\", "/")
            found.append(rel)
    return found


def category_for(rel):
    lowered = rel.lower()
    if lowered.startswith("vsdk/"):
        return "vsdk"
    if lowered.startswith("levelscripts/"):
        return "scripts"
    if lowered.startswith("summoner/"):
        return "game"
    return "engine"


def write_objdiff(units):
    payload = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "custom_make": "ninja",
        "build_target": False,
        "build_base": False,
        "watch_patterns": ["*.c", "*.cpp", "*.h", "*.py", "*.yml", "*.yaml", "*.txt", "*.json"],
        "ignore_patterns": ["build/**/*", "VPP/**/*", "baserom/**/*"],
        "progress_categories": [
            {"id": "engine", "name": "Engine"},
            {"id": "vsdk", "name": "Volition SDK"},
            {"id": "game", "name": "Game"},
            {"id": "scripts", "name": "Level scripts"},
        ],
        "units": [
            {
                "name": rel,
                "target_path": None,
                "base_path": None,
                "metadata": {
                    "source_path": "src/" + rel,
                    "progress_categories": [category_for(rel)],
                },
            }
            for rel in units
        ],
    }
    with open(os.path.join(ROOT, "objdiff.json"), "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")


def _symbol_rows(path):
    rows = []
    with open(path, "r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 3:
                continue
            rows.append((parts[0], parts[1], parts[2]))
    return rows


def _entity_type(name):
    if name.startswith("crt_") or name in {
        "MoveFileA",
        "DeleteFileA",
        "GetLastError",
        "GetFileAttributesA",
        "GetCurrentDirectoryA",
        "SetFileAttributesA",
    }:
        return "library"
    if name.startswith("g_"):
        return "global"
    return "function"


def write_reccmp_csv():
    """Address list in the form reccmp reads.

    Every function from config/symbols_all.txt is included. That file is the
    decomp-toolkit scan of Sum.exe plus the names already in symbols.txt.
    """
    import re

    pattern = re.compile(
        r"(\S+) = \.\w+:0x([0-9A-Fa-f]+); // type:(\w+)(?: size:0x([0-9A-Fa-f]+))?"
    )
    path = os.path.join(ROOT, "config", "symbols_all.txt")
    rows = []
    with open(path, "r", encoding="utf-8") as handle:
        for raw in handle:
            match = pattern.match(raw.strip())
            if not match:
                continue
            name, address, kind, size = match.groups()
            if kind == "function":
                csv_type = "function"
            elif kind == "object":
                csv_type = "global"
            else:
                csv_type = "function"
            size_cell = f"0x{size}" if size else ""
            rows.append((address, name, csv_type, size_cell))
    destination = os.path.join(ROOT, "config", "reccmp.csv")
    with open(destination, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("address|name|type|size\n")
        for address, name, csv_type, size_cell in rows:
            handle.write(f"0x{address}|{name}|{csv_type}|{size_cell}\n")
    return len(rows)


def write_ninja():
    text = """\
# Generated by configure.py. Matching objects are not produced yet.
rule progress
  command = python tools/progress.py --report build/report.json
  description = progress

rule extract
  command = python tools/extract_game.py
  description = isolate Sum.exe and link retail archives

build progress: progress
build extract: extract
default progress
"""
    with open(os.path.join(ROOT, "build.ninja"), "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def main():
    rels = modules()
    write_objdiff(rels)
    write_ninja()
    from tools.build_symbols import write_symbols

    text_count, _covered = write_symbols()
    marked = write_reccmp_csv()
    print(
        f"wrote objdiff.json ({len(rels)} units), build.ninja, "
        f"config/symbols_all.txt ({text_count} .text symbols), "
        f"and config/reccmp.csv ({marked} addresses)"
    )


if __name__ == "__main__":
    main()
